version: "3"
services:
  app:
    restart: always
    build: .
    command: yarn host:prod
    environment:
      PORT: 3000
      API_URL: "API_URL"
    volumes:
      - .:/app/
    ports:
      - "3000:3000"
